- name: Configure global git properties
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_config }}"

- name: Add global .gitignore
  copy:
    src: gitignore
    dest: ~/.gitignore
