ansible_connection: local
ansible_python_interpreter: "{{ansible_playbook_python}}"
dockitems_remove:
  - App Store
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Pages
  - Photos
  - Reminders
  - Safari
  - System Settings
  - TV
dockitems_persist:
  - name: Arc
    path: /Applications/Arc.app
    pos: 1
  - name: Asana
    path: /Applications/Asana.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: LastPass
    path: /Applications/LastPass.app
    pos: 4
  - name: Obsidian
    path: /Applications/Obsidian.app
    pos: 5
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 6
git_config:
  - name: diff.tool
    value: vimdiff
  - name: difftool.prompt
    value: "false"
  - name: alias.d
    value: difftool
  - name: user.name
    value: "{{ lookup('env', 'WORK_NAME') }}"
  - name: user.email
    value: "{{ lookup('env', 'WORK_EMAIL') }}"
  - name: user.signingkey
    value: "{{ lookup('env', 'WORK_GPG_KEY') }}"
  - name: commit.gpgsign
    value: "true"
  - name: init.defaultbranch
    value: main
  - name: core.commentchar
    value: auto
  - name: core.excludesfile
    value: ~/.gitignore
  - name: core.autocrlf
    value: input
  - name: gpg.program
    value: /usr/local/bin/gpg
homebrew_cask_accept_external_apps: true
homebrew_cask_apps:
  - arc
  - asana
  - aws-vpn-client
  - brewservicesmenubar
  - docker # actually installs docker desktop
  - google-cloud-sdk
  - google-drive
  - gpg-suite-no-mail
  - iterm2
  - jetbrains-toolbox
  - keybase
  - lastpass
  - logi-options-plus
  - loom
  - notion
  - obsidian
  - session-manager-plugin
  - skitch
  - slack
  - spotify
  - sublime-text
  - tuple
  - webex
  - yubico-authenticator
homebrew_installed_packages:
  # AWS packages
  - amazon-ecs-cli
  - awscli
  - eksctl
  # Development
  - gh
  - git
  - go
  - gradle
  - helm
  - heroku
  - nvm
  - openssl@1.1
  - openssl@3
  - postgresql@15
  - python@3.12
  # Docker packages
  - docker-credential-helper
  # MongoDB packages
  - mongodb-community
  - mongodb-database-tools
  - mongosh
  # Network tools
  - ipcalc
  - nmap
  - speedtest-cli
  - tcptraceroute
  # Python packages
  - poetry
  # Terraform packages
  - tflint
  - tfsec
  - tfswitch
  # Utiliies
  - dos2unix
  - grep
  - jq
  - jsonlint
  - keyring
  - mas
  - openjdk
  - pinentry
  - pinentry-mac
  - readline
  - thefuck
  - wget
  - zsh
homebrew_taps:
  - heroku/brew
  - homebrew/services
  - mongodb/brew
  - warrensbox/tap
homebrew_cask_uninstalled_apps: []
homebrew_uninstalled_packages:
  # These packages provide CLI tools only. We need Docker Desktop to run containers.
  - docker
  - docker-completion
homebrew_upgrade_all_packages: true
mas_installed_apps:
  - id: 1252988123
    name: RegEx Lab
omz_plugins:
  - git
  - docker
  - brew
  - bundler
  - branch
  - colored-man-pages
  - command-not-found
  - dotenv
  - gem
  - git-prompt
  - macos
  - python
  - rails
  - ruby
  - rvm
  - rsync
  - ssh-agent
  - sudo
  - terraform
  - thefuck
  - thor
  - aws
zsh_aliases:
  - name: be
    command: bundle exec
