
- name: Install dependencies for work
  hosts: localhost
  become: false
  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - role: omz
      vars:
        plugins: "{{ omz_plugins }}"
      when: omz_plugins is defined
    - role: zsh
